### ISSUE TITLE
todo: information fields

### ISSUE THREAD

**Issue by blocktrron** [blocktrron/gluon-diagnostic#1]
- [ ] System load
- [ ] Firmware Version
- [ ] WAN IP Address state
- [ ] Connected clients in last 24h

**Comment by grische** [comment]
AFAICT this has already been implemented, hasn't it?

personally, I would like to add:
- [ ] board name (i.e. model name)

And potentially,  but this might need some discussion:
- [ ] contact information if present and exposed
